name: Build Pear Desktop Linux Arch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: {}

env:
  NODE_VERSION: "22.x"

jobs:
  build:
    permissions:
      contents: write
    if: github.event.pull_request.draft == false
    name: Build Pear Desktop Linux Arch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 10
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Vite Build
        if: github.repository != 'pear-devs/pear-desktop' || github.event_name == 'pull_request'
        run: |
          pnpm build

      - name: Build and release on Linux Arch
        if: github.repository == 'pear-devs/pear-desktop' && github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm clean && pnpm build && pnpm electron-builder --linux tar.gz:x64 -p always
